"""
Inference service — Churn Intelligence v2.0
==========================================
Orchestrates advanced feature engineering and prediction using the XGBoost pipeline.
Integrates the new segmentation and temporal decay logic into the production API.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import pandas as pd
import joblib
import numpy as np

# Add ml-pipeline to path for core modules
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "ml-pipeline"))

from preprocessing.clean             import clean
from preprocessing.feature_engineering import engineer_features, encode_and_scale
from models.predict                  import _get_segment, _get_recommendation
from app.core.logger import get_logger

logger = get_logger(__name__)

# Path to artifacts generated by main pipeline
MODEL_PATH = PROJECT_ROOT / "ml-pipeline" / "outputs" / "xgb_model.pkl"
SCALER_PATH = PROJECT_ROOT / "ml-pipeline" / "outputs" / "scaler.pkl"

class InferenceService:
    def __init__(self):
        self.model = None
        self.scaler = None
        self._load_artifacts()

    def _load_artifacts(self):
        try:
            if MODEL_PATH.exists():
                self.model = joblib.load(MODEL_PATH)
            if SCALER_PATH.exists():
                self.scaler = joblib.load(SCALER_PATH)
        except Exception as e:
            logger.error(f"Failed to load ML artifacts: {str(e)}")

    def _get_risk_level(self, score: float) -> str:
        if score > 0.7: return "HIGH"
        if score > 0.3: return "MEDIUM"
        return "LOW"

    def predict_one(self, raw: dict[str, Any]) -> dict[str, Any]:
        """
        Predict churn for a single user using v2.0 intelligence.
        """
        user_id = raw.get("user_id", raw.get("customer_id", "unknown"))
        logger.info("Single inference v2.0 request", extra={"user_id": user_id})

        if not self.model or not self.scaler:
            raise RuntimeError("ML model or scaler not loaded. Run the pipeline first.")

        # Convert to DataFrame for processing
        df = pd.DataFrame([raw])
        if "user_id" in df.columns:
            df = df.rename(columns={"user_id": "customer_id"})

        # Pipeline: Clean -> Engineer -> Scale -> Predict
        df_clean = clean(df)
        df_feat  = engineer_features(df_clean)
        X, _, _, _ = encode_and_scale(df_feat, fit_scaler=False, scaler=self.scaler)

        # Predict
        proba = float(self.model.predict_proba(X)[:, 1][0])
        
        # Segment & Recommendation
        monetary_p80 = 80.0  # Fallback if distribution stats not available
        segment = _get_segment(df_feat.iloc[0], monetary_p80)
        recommendation = _get_recommendation(segment)

        return {
            "user_id": user_id,
            "churn_score": round(proba, 4),
            "risk_level": self._get_risk_level(proba),
            "segment": segment,
            "recommendation": recommendation
        }

    def predict_many(self, records: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """
        Batch prediction using v2.0 intelligence.
        """
        if not self.model or not self.scaler:
            raise RuntimeError("ML model or scaler not loaded.")

        df = pd.DataFrame(records)
        if "user_id" in df.columns:
            df = df.rename(columns={"user_id": "customer_id"})

        df_clean = clean(df)
        df_feat  = engineer_features(df_clean)
        X, _, _, _ = encode_and_scale(df_feat, fit_scaler=False, scaler=self.scaler)

        probas = self.model.predict_proba(X)[:, 1]
        
        results = []
        for i, proba in enumerate(probas):
            score = float(proba)
            uid = records[i].get("user_id", records[i].get("customer_id", f"user_{i}"))
            results.append({
                "user_id": uid,
                "churn_score": round(score, 4),
                "risk_level": self._get_risk_level(score)
            })
        
        return results

inference_service = InferenceService()
